version: '3.8'

services:

  frontend:
    container_name: front
    build:
      context: ../frontend
  backend:
    build: ../backend
    container_name: backend
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - bd
    environment:
      CORS_ORIGINS: ${CORS_ORIGINS}

  mongo-keygen:
    container_name: mongo-keygen
    build:
      context: .
      dockerfile: Dockerfile.keygen
    restart: "no"
    command: >
      sh -c "
        mkdir -p /keyfile && \
        openssl rand -base64 756 > /keyfile/mongo-keyfile && \
        chmod 400 /keyfile/mongo-keyfile && \
        ls /keyfile 
      "
    volumes:
      - mongo-keyfile:/keyfile

  db:
    build:
      context: ./mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: master
    depends_on:
      mongo-keygen:
        condition: service_completed_successfully
    volumes:
      - mongo_data:/data/db
      - mongo-keyfile:/mongo-keyfile
    healthcheck:
      test: [ "CMD", "mongosh", "--host", "localhost", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 2s




volumes:
  mongo_data:
  mongo-keyfile:

