version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/foo/swagger.yml
    volumes:
      - ../swagger:/foo
